#!/bin/bash

# generate-env.sh
# Generates .env file with consistent secrets for docker-compose

set -e

ENV_FILE="$(dirname "$0")/.env"

echo "Generating environment file for docker-compose..."

# Generate random Redis password if not exists
if [ ! -f "$ENV_FILE" ] || ! grep -q "redis_password=" "$ENV_FILE" 2>/dev/null; then
    REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)
else
    REDIS_PASSWORD=$(grep "redis_password=" "$ENV_FILE" | cut -d'=' -f2)
fi

# Generate random JWT secret if not exists  
if [ ! -f "$ENV_FILE" ] || ! grep -q "JWT_SECRET=" "$ENV_FILE" 2>/dev/null; then
    JWT_SECRET=$(openssl rand -base64 64 | tr -d "=+/" | cut -c1-64)
else
    JWT_SECRET=$(grep "JWT_SECRET=" "$ENV_FILE" | cut -d'=' -f2)
fi

# Write .env file
cat > "$ENV_FILE" << EOF
# Docker Compose Environment Variables
# Generated by generate-env.sh

# Redis Configuration
redis_password=$REDIS_PASSWORD

# JWT Configuration  
JWT_SECRET=$JWT_SECRET
EOF

echo "Environment file created: $ENV_FILE"
echo "Redis password: [HIDDEN - $((${#REDIS_PASSWORD})) characters]"
echo "JWT secret: [HIDDEN - $((${#JWT_SECRET})) characters]"
echo ""
echo "Usage:"
echo "  docker-compose up -d                    # Start all services"
echo "  docker-compose run jwt-signer -list     # List token presets"
echo "  docker-compose run jwt-signer -preset=user1  # Generate user token"